### ISSUE TITLE
Science wing moves up with elevator

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#101]
![image](https://github.com/paulkim26/collab-museum/assets/45007945/b0c1a841-a45f-46b2-8f66-57e393f75b3e)

**Comment by paulkim26** [comment]
Should also note science wing should have unloaded by this point already

**Comment by chazzybuch** [comment]
Oof didn't experience that one at all in any of my running around. Repro steps?

**Comment by paulkim26** [comment]
Also science wing music is still playing

**Comment by chazzybuch** [comment]
K something broke, one minute

**Comment by chazzybuch** [comment]
Sounds like render out lock didnt trigger properly

**Comment by chazzybuch** [comment]
Just curious did you use debug to open door?

**Comment by paulkim26** [comment]
Nope, used the "scan" tablet
