### ISSUE TITLE
Add Science wing easter egg

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#122]
Just adding this a reminder for myself if time / resources permit

**Comment by FranchNotFrench** [comment]
This is the flying horse? If so seems safe to close.

**Comment by paulkim26** [comment]
If by flying horse you mean the one visible from history section, no that's my Easter egg.

**Comment by FranchNotFrench** [comment]
Oh right, I got the sections confused. I'm not sure what the Science Easter
egg entails.

I don't currently have any Easter eggs in the central hub or atrium.

**Comment by chazzybuch** [comment]
Putting this on pause as a maybe thing for after release if I have time / it doesnt break anything. Not worried about it either way
