### ISSUE TITLE
VIP door logic can be inverted

### ISSUE THREAD

**Issue by wollo77** [paulkim26/collab-museum#125]
If you use the VIP pass on the door scanner twice (i.e. use it a second time while it is already open), the door logic is inverted, i.e. it closes if you go near it and opens while you are away.

**Comment by FranchNotFrench** [comment]
I have noticed this inversion but I didn't realize it was tied to the card reader; I've triggered it several times but I don't remember scanning while the door is open or in the process of closing. Hopefully that is the only cause; I will investigate.

**Comment by paulkim26** [comment]
Non-vip doors can invert as well if you step in/out of triggers quick enough, hard to reproduce tho

**Comment by paulkim26** [comment]
I suggest keeping vip doors permanently open if they can't be guaranteed to invert/trap & soft lock players

**Comment by FranchNotFrench** [comment]
> Non-vip doors can invert as well if you step in/out of triggers quick enough, hard to reproduce tho

The non-VIP doors currently have On Enter and On Exit actions to trigger the door animation, I'm wondering if disabling the trigger briefly after one of these fires would eliminate these from firing simultaneously. Seems like it.
