### ISSUE TITLE
Token pick-up sound plays whenever an area renders out, and then renders in again

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#145]
This is due to tokens being parented to wing's interior empties. In some cases (see Science wing), this could be difficult to get around if tokens/triggers are parented directly to moving objects, which are part of puzzles, which are part of the wing.

Need to develop workaround.

**Comment by paulkim26** [comment]
Can we parent the tokens under the lobby drag empty? That way they never render out

**Comment by chazzybuch** [comment]
Yeah that'd be the simple solution for the static ones. Just would like to
try to sort something out for any that would be on animated objects (which
I think is only my 2 in science). Think I gotta solution, just want to make
sure its the most efficient one, using as little extra logic as possible.

**Comment by paulkim26** [comment]
oh right forgot about those

**Comment by chazzybuch** [comment]
If it becomes a bag of squirrels after my first crack at it, theyll become
static. Definitely want a relatively simple solution that isnt going to
cause extra unnecessary troubleshooting down the line
