### ISSUE TITLE
Medallions don't show up if all locks are bypassed

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#146]
The medallion is supposed to show up when no more keys are needed, which is the case when all three sections have been unlocked.

This is currently working if you use the starting key and bypass the other two sections, but if you don't use the starting key and bypass all three sections, the medallion doesn't show up. While unlikely, it would be good for the logic to handle this situation as well.

I can't reproduce this in my published Central hub, so perhaps the logic changed during the merge. If so, it might be helpful to look at how it was originally working in my version.

**Comment by paulkim26** [comment]
Fixed in #148
