### ISSUE TITLE
2nd floor performance optimizations

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#162]
Assets on 2nd floor need further optimization.

FPS as of #148: 103 FPS
![image](https://github.com/paulkim26/collab-museum/assets/45007945/d4355bf4-fd84-4508-b7db-7c1f44a224eb)

FPS as of #159: 48 FPS
![image](https://github.com/paulkim26/collab-museum/assets/45007945/f2ce953f-598f-495f-b81f-dcd34cff9cbb)

Testing criteria:
- GPU: RTX 3080
- settings: all max
- resolution: 1440p

**Comment by paulkim26** [comment]
Benchmarks with Steam Deck

FPS as of #148: 48 FPS
![PXL_20230623_235324269 MP](https://github.com/paulkim26/collab-museum/assets/45007945/cf2b7f26-f0e6-42a6-b6df-48730941ec8b)

FPS as of #159: 23 FPS
![PXL_20230623_233943369](https://github.com/paulkim26/collab-museum/assets/45007945/6b1dfb77-ae92-442d-a5e8-6442776ed22e)

**Comment by chazzybuch** [comment]
Going to do little further investigating. Didn't think of it earlier, but I think adjusting / reducing the pre-existing Lounge lighting will be a big piece of it. Bar mirror and piano also look like they're causing big hits. Toggling off all 3 of these seems to give the biggest performance increase.

**Comment by paulkim26** [comment]
FPS as of #168: 54 FPS

![image](https://github.com/paulkim26/collab-museum/assets/45007945/9633eadd-2702-4af4-b63a-9d2ebde56454)

**Comment by FranchNotFrench** [comment]
Minor optimization in #185 - two fewer lounge lights (eliminated two of the four overhead lights that seemed to have the biggest impact) and lowered range of all remaining lounge lights.

**Comment by FranchNotFrench** [comment]
Before deleting, in general my preference is to try shrinking ranges and adjusting angle/intensity to compensate for lack of range, but happy to delete if it comes to that.

**Comment by paulkim26** [comment]
Ongoing task.
