### ISSUE TITLE
Copper pots break in the lounge.

### ISSUE THREAD

**Issue by Thoroniul** [paulkim26/collab-museum#166]
One throws an object at it and the pieces go flying everywhere.

**Comment by paulkim26** [comment]
Unable to find any breakable pots in lounge. May have been fixed and not closed. The two I found are:
![image](https://github.com/paulkim26/collab-museum/assets/45007945/e5b53d1d-4f59-4ed1-9ecd-fb7075dc8dbf)
![image](https://github.com/paulkim26/collab-museum/assets/45007945/e32b6242-284d-4de8-94e2-8508a0a5611f)

**Comment by paulkim26** [comment]
Can you confirm if these are the pots that were breakable?

**Comment by paulkim26** [comment]
@Thoroniul feel free to re-open if you can provide a repro

**Comment by paulkim26** [comment]
repro: throw a key downward on a pot with a charge attack
