### ISSUE TITLE
Hide debug stuff before final launch

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#174]

**Comment by paulkim26** [comment]
itty bitty lil cube
![image](https://github.com/paulkim26/collab-museum/assets/45007945/a5c38777-aa20-43b5-bbc6-dba0b953a6bc)

**Comment by FranchNotFrench** [comment]
I replaced Chazzy's moon with a cube to see if he'd notice. #performance
(jk)

**Comment by paulkim26** [comment]
Duplicate to #288

**Comment by FranchNotFrench** [comment]
The difference in my mind was hide vs delete. We probably have 100+ debug
objects that we don't really need anymore.

In terms of hiding, I think we just need to decide when to hide the main
debug switch by default. Or we could try to leave it functional but tiny
and in a really sneaky place?

**Comment by paulkim26** [comment]
Ah gotcha. Didn't mean either hide or delete specifically in this issue, just get rid of from player experience. Yes let's delete whatever we can. I'm open to either way of concealing the debug toggle

**Comment by paulkim26** [comment]
If we simply conceal the debug controls in the room there's a small chance players can find it, but it's not a big deal if they do

If we move it out of reach, editors can move it back in when they're in editor, they may forget after and leave it hanging around in the lobby, but the PR reviewer should catch that anyways

**Comment by FranchNotFrench** [comment]
The only reason I can think of to make it available in the published
version is if we need to debug something that is behaving differently in
the editor vs published version. Otherwise, we can always turn it back on
in the editor.

**Comment by paulkim26** [comment]
Yes might as well make it inaccessible to players
