### ISSUE TITLE
Exit door colliders / obstacle

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#179]
I'm not sure what is happening or if this is reproduceable, but twice today I was able to clip through the exit doors with my back to them, but not while facing them. It's not an ES bug I've heard of before. Just leaving a note here to do more testing.

**Comment by FranchNotFrench** [comment]
Ah it's missing an obstacle in front of it. The doors are in the base game and have Obstacle turned on, but that seems to be insufficient. Easy fix though.

**Comment by paulkim26** [comment]
Sounds good, also the collider for the exit doors is weird, need to be really close to it, not sure if issue opened already

**Comment by FranchNotFrench** [comment]
I think Wollo fixed this and I tested it in a playthrough...I just didn't
look at it in the editor since it was either part of a different PR or I
forgot. But I noticed the Colliders are fixed.
