### ISSUE TITLE
Blue volumetric light for Bobblehead

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#180]
The blue volumetric light for the bobblehead seems to have a mind of its own. I have reset its position next to the other two lights several times but it seems to keep showing up elsewhere and I'm not sure why. In the latest published version it is the furthest away I have seen - across the room.

**Comment by paulkim26** [comment]
Noticed this too, not sure why

**Comment by FranchNotFrench** [comment]
I can try to redo the parenting...maybe something funky happened. Or just deleting it and placing it again.

**Comment by FranchNotFrench** [comment]
I redid all the parenting and unskewed the empties, so this should be fixed for now with #185
