### ISSUE TITLE
Decimate central whale model

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#195]
`mdl_zesty_whale.gltf` currently 223k faces

**Comment by FranchNotFrench** [comment]
If you're using Blender, makes sure you apply the changes to the decimate modifier (there is also an option to apply all modifiers on the Export settings screen).

**Comment by paulkim26** [comment]
Thanks for the reminder. I do remember checking the gltf file I generated and confirming the face count was decimated, so this looks like a case of just not putting the model into the repo 🤦‍♂️
