### ISSUE TITLE
Section Completed on screen text appears immediately if you use the bypass and access a section

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#203]
Is this a known issue? Related to the walkthrough + Puzzle logic? If you bypass a lock to access a section, it seems like it shouldn't immediately tell you that you've completed it.

**Comment by FranchNotFrench** [comment]
Maybe I misinterpreted this and it is just telling me the Section Entrance was completed? That's what Gallery says. But it still seems like an odd thing to tell the player since they haven't really accomplished anything yet.

**Comment by paulkim26** [comment]
Noticed this too, not sure why that is

**Comment by paulkim26** [comment]
@chazzybuch do you know about the section completed message that shows up for the section entrances?

**Comment by chazzybuch** [comment]
Hmm no wasnt aware of this. It's currently set to trigger only once the
wing key / medallion is removed from its trigger. Not sure if its something
around a key being swapped to medallion once two other wings are unlocked?

**Comment by FranchNotFrench** [comment]
Example 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/7bbc4fac-d177-4f75-b425-e2cc173f84eb)

This shows up after clicking History bypass and clicking on double doors

**Comment by chazzybuch** [comment]
This is normal behavior for all wings. The "Entrance" is completed when you
first open any wing, and all puzzle walkthroughs for the wing are unlocked.
They are all then hidden one by one as you complete puzzles.

**Comment by paulkim26** [comment]
Ah gotcha

**Comment by FranchNotFrench** [comment]
Is it possible to suppress the Entrance ones and only use the status
updates for solving puzzles?

**Comment by chazzybuch** [comment]
With the new update that came out yesterday it might be now. Would have to
check.

**Comment by wollo77** [comment]
Just tested it: With the new update, no text will be shown if you just leave the puzzle name empty.
This will also allow us to add special handling for the meta puzzles (only showing their solutions once they become available/solvable)
The sound can also be disabled now, but I think it works fine, so I'd leave that as is.
