### ISSUE TITLE
Gallery floor pop-ups should probably be obstacles

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#208]
I didn't test them all, but the ones I ran through didn't have obstacles.

**Comment by paulkim26** [comment]
You're talking about the little compartments that rise up from the gallery floor when a puzzle is solved?

**Comment by FranchNotFrench** [comment]
Yes, those cubes. Makes sense to avoid soft locks though.

**Comment by FranchNotFrench** [comment]
I will close
