### ISSUE TITLE
Hide some (all?) items in the Atrium when player is on the Ground floor

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#222]
Any items that can't be seen from below can be safely hidden. Even some items that can be seen might be worth hiding for performance (okay to cheat a bit here, per Zesty).

**Comment by chazzybuch** [comment]
Is there anything we feel we could reposition / move away from the balconies to maximize this?

**Comment by FranchNotFrench** [comment]
I think it would be tough...the balconies are pretty narrow to begin with, and the rooms could kind of lopsided if we shove everything into the back half. But maybe there are things where we can simplify them, i.e. hide part of them like you did with the snow globe. I'm still not sure this would help performance too much. The stuff by the railings is pretty simple.

I haven't tested this, but I'm guessing the ceiling tiles impact performance a bit given the sheer number of them. Each of the four tiled roofs is paired to an empty which is the center of their radius (and how I built them) so it would be pretty easy to test what happens with them rendered out. Not that we can render them out, but it would be possible to replace with a similar model that reduces this to four objects and very simple geometry.

**Comment by chazzybuch** [comment]
Yeah, sorry once again I need to shut up after being gone for 4 days. Gonna hold off on making any more comments until I get caught up more thoroughly. Been a weird week and my brain is just readjusting to Collab mode

**Comment by FranchNotFrench** [comment]
Glad to have you back!! Apologies in advance for playing with the exterior lighting. I attempted to leave the original lights you have and set them to 0 intensity and to document what they were before in case you want to roll back to them or test the difference, rather than deleting. Your buttons are all still there. The one thing I'm confident in is that City Glow Directional is not a good option - it makes too many things orange that really shouldn't be. Performance aside, Moon Directional looks great.

**Comment by FranchNotFrench** [comment]
Reminder: could also toggle Creator Card Lua script with a viz activator so it is only enabled when players are upstairs.
