### ISSUE TITLE
Snow Globe gift shop item - when to disable?

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#223]
Currently there is logic to enable the snow globe in the gift shop when either Gift shop door is opened (it is disabled from the start). However, this appears to be a one-time thin, i.e. it isn't disabled again as far as I can tell.

If someone does not buy the snow globe and leaves the gift shop, there could be logic to hide it again (but would need to be disabled if purchased). Marking this as a low priority / feel free to close.

**Comment by chazzybuch** [comment]
Once we get the balloon logic fully in, I can set it to disable once the ride is activated if the snowglobe still sits in its place without the player having grabbed it. There would be a lot of stuff we'd ideally be rendering out when this happens.

**Comment by chazzybuch** [comment]
Also if we keep the gift shop cases away from the balcony this is probably one area we could fully render out until the elevator travels up. If we could manage to do this for all or most sections this would really benefit performance on the 1st floor.

**Comment by FranchNotFrench** [comment]
Zesty said that he's okay cheating a bit for performance, i.e. hiding some
balcony things that technically can be seen from below. I set up an issue
as a reminder to sort this out.

I'm guessing performance will be okay though if we don't hide the things by
the railings. I agree we can try to minimize stuff by the railings but the
birdcage and piano and centered creator card stand can't really move back,
and I kind of like using the area in the gift shop corners and/or bump out
for cases to space them out and their lighting.

**Comment by FranchNotFrench** [comment]
I think this is currently working as intended (I disable some items while on the main floor and during the balloon ride). I don't hide the display cases during the balloon ride but could probably hide the snow globe since it would be hard to see. I don't expect it would have much of a performance boost though. Marking complete for now. If we want to revisit, there is an activator by the rest of the Balloon logic that controls what gets de-rendered during the balloon flight after the teleport into the balloon.
