### ISSUE TITLE
Check Creator Card collision

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#224]
The creator card bases are already an obstacle, but visually I think I can clip through the frames right now so the obstacle might need to be bigger or maybe the frames can be obstacles (not currently set to Is Obstacle). The new card models need to have their colliders disabled to avoid interfering with the frames that are now the buttons (it is already this way).

**Comment by chazzybuch** [comment]
With the frames rotating I would not set them as "Is Obstacle" as this will likely just cause players to constantly get stuck.

Also I know we landed on using LUA to start/stop rotation of the player cards, and while I do really like the functionality, I believe this is our only remaining LUA script that hits .Update. It may be worth comparing performance with normal empty rotations, or no rotations at all. An easy test would be stopping the LUA script from activating during the elevator ride and see if there were any noticeable performance gains.

**Comment by FranchNotFrench** [comment]
Good call on obstacles.

I think at some point I made a test button that disabled the script, which
you can target with a viz activator to toggle rotation on or off. I don't
remember thinking it improved fps though.

Is there a way to do with without .update?

**Comment by FranchNotFrench** [comment]
I like the rotation, but if we can't find a way to disable it based on proximity, I'd still prefer no rotation to constant rotation.

**Comment by chazzybuch** [comment]
Yeah I apologize I'm just running through your latest edits and I'll retract that. Performance seems pretty solid all around upstairs right now. In our next multiplayer playtest we can see how things look, but I'm also hoping we can get away with the LUA rotations on those as I'd prefer keeping them as well.

**Comment by wollo77** [comment]
Please see #231 for a script version that no longer uses Update (and has other optimizations).

**Comment by FranchNotFrench** [comment]
I'm going to mark this as complete/won't fix. The current collision / obstacles are behaving as intended.
