### ISSUE TITLE
Piano keys disappear

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#226]
![image](https://github.com/paulkim26/collab-museum/assets/45007945/29b6fcf1-fbaf-45e1-9a8e-833c39fa5273)

**Comment by paulkim26** [comment]
Seems to happen randomly when opening/closing the lid multiple times, i.e. after 3 times

**Comment by FranchNotFrench** [comment]
Thanks...I haven't seen that happen. I'll check the logic.

**Comment by wollo77** [comment]
Happens specifically when you click it twice while it's open.
Apparently, the disappearing is done with a delay, and the appearing is not, so if you click twice, the appearing will happen before the disappearing.

**Comment by FranchNotFrench** [comment]
Thanks, that makes sense and an oversight on my part. What I typically do to address that is disable the collider so it can't be clicked again until after the delay. These asymmetrical viz toggles usually trip me up somewhere.
