### ISSUE TITLE
The Active Section is still hidden if you take the elevator back downstairs

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#245]
How to reproduce (tested with both Gallery and History):
1) Activate a section
2) Go upstairs then go back downstairs.
3) Re-enter the Active section...it will be invisible.

Not sure the easiest way to fix this...either de-activate the current Section when players go upstairs? Or do a viz toggle for the active section if players go back downstairs.

**Comment by FranchNotFrench** [comment]
I was able to reproduce this in the published version as well, confirming this isn't something I broke when messing around with Music logic today.

**Comment by FranchNotFrench** [comment]
The music logic would work better if the active section is completely disabled when players go upstairs, which seems consistent with the upstairs being a fourth section and only one active section at a time. The music logic is set to restart the section loop music when players re-activate it, which wouldn't happen if the Atrium loop starts and then they run back down to the section that is still currently active.

**Comment by chazzybuch** [comment]
I'll take a look. We implemented some safeties that may be superfluous now and messing things up

**Comment by FranchNotFrench** [comment]
I think Chazzy fixed this yesterday but I still need to test, unless someone already did and can close.

**Comment by chazzybuch** [comment]
Yes I believe this should be all set now
