### ISSUE TITLE
Science Entry: two messages shown at once, and inversion

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#257]
I'm not exactly sure how I caused these, but I was running back and forth between Science and History. Typically I also use debug to grab the Science key on the first visit. In the second screenshot I have History and Science both loaded at the same time, and I can't get the Science doors to close unless I click on the Science sign.

![image](https://github.com/paulkim26/collab-museum/assets/114628499/f513b424-1790-494a-878c-aee8bc971a7d)
![Uploading image.png…]()

**Comment by FranchNotFrench** [comment]
Somehow it lost my first screenshot but it was both sign messages shown at the same time: Request access scan, and Science Wing access

**Comment by FranchNotFrench** [comment]
Probably related, if I go to Science + grab the key, use it on History, then go back to Science and hit the access scan, the trigger doesn't want to open the doors unless I run back out towards the lobby and then back towards the door. It triggers when I exit the trigger but then when I re-enter it starts closing and I can't get in (this is with Science unlocked) so seems like the same inversion.

**Comment by FranchNotFrench** [comment]
Not sure if this is related, but I was running back and forth between Gallery, History, and Atrium a bunch of times, and at some point this prop was visible and stayed visible. I never activated Science on this run through. 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/e484e6f8-098e-4a3f-ad59-45588b95f5c0)

**Comment by FranchNotFrench** [comment]
It isn't parented to Drag Lobby, so I could see it sticking out in the lobby when I rode the elevator up.

**Comment by FranchNotFrench** [comment]
This may not be helpful, but I notice that sometimes when Science unlocks on re-entry (I click request access and access is granted), the Main Section Unlock does not seem to be firing. I can tell this because I'm using that lock to reset the pins on my re-entry music logic lock, on a 0.2 second delay. It works once but then not again.

How to reproduce:
1) Turn on Debug and Unlock Science for the first time. Note the Science Re-entry logic display goes from 000 to 220, meaning that the Main Access ON lock unlocked.
2) Unlock another section. Note the Science Re-entry logic display goes from 220 to 210, meaning another section is currently active (middle pin).
3) Access Science a second time. Note the Science Re-entry logic display goes from 210 to 221, meaning that the Main Access ON lock unlocked, and it is also setting the Rightmost pin indicating that Science has now been accessed 2+ times and the re-entry lock is permanently primed.
4) Access another section. 3) Access Science a second time. Note the Science Re-entry logic display goes from 221 to 211, meaning that the Main Access ON lock unlocked,  meaning another section is currently active (middle pin) but that the re-entry music loop logic lock remains primed (rightmost pin).
5) Access Science a third time. Note the Science Re-entry logic display goes from 211 to 111, meaning that the Main Access ON lock did not successfully unlock and set the leftmost pin back to 2 as it did the other two times (unless there is some other reason for this I am missing).

If you continue accessing Science and then another section, it works as expected every other time; on the cycles where it doesn't work, accessing another section also doesn't restart that section's music, which also implies the main Science Access ON lock is not unlocking half the time because that is what drives the other sections re-enter logic locks to know if Science (or another section) is currently active.

**Comment by FranchNotFrench** [comment]
Here's a breakdown of the re-entry logic locks, with password 1-1-1:

Pin 0: Unlock check, driven by Main Access ON lock. Goes to 1 every time the main Section ON lock unlocks, and then goes to 2 0.2 seconds later triggered by that same lock to reset it.

Pin 1: Other section active check. Goes to 1 every time another section Access ON lock unlocks, or Elevator UP lock unlocks. Resets to 2 when the section Access ON lock unlocks (same as Pin 0).

Pin: Goes to 1 when section has been accessed twice, determined by small Continuous lock with password 1-1 that is connected to section Access ON lock. This pin never gets reset and permanently primes the re-entry logic lock, which then just checks to see if the section is being re-activated (pin 0) and if another section is currently active (pin 1).

**Comment by chazzybuch** [comment]
Unfortunately wasn't able to reproduce this when looking into it for my latest PR. Also the Art wing spotlights seemed to be properly parented to the Art Interior empty, so not sure if you made this change or this was already the way it was.

**Comment by chazzybuch** [comment]
The Science Access ON lock should be getting hit every time the Science access tablet is used, whether using the "Request Access" or "Science Wing Access" buttons. So not sure what would be causing this.

**Comment by FranchNotFrench** [comment]
Thanks for looking into this. I'll take a closer look as well.

I didn't parent the Gallery lights but I'm guessing Wollo did.

**Comment by FranchNotFrench** [comment]
I'm still able to break the Science doors if I run out of the trigger while the animation is playing. 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/f2456ba2-d2bd-4825-945f-0415fc1327f2)

**Comment by FranchNotFrench** [comment]
![image](https://github.com/paulkim26/collab-museum/assets/114628499/ca5f0367-64c4-4629-950e-7106642251c1)
