### ISSUE TITLE
Wording suggestions from k8sparrot

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#270]
Source: https://discord.com/channels/449578254433517578/1124175407860695121/1125991463210188870

> English in Art room – K01 (really minor one) – should say “…abstract pieces…” (not piece). N03 – “The keyhole can often be…” (add word “can”).  In Science room – nothing really, just a missing period in N06 (before “Very”). And that’s it from me, couldn’t even break anything!

**Comment by FranchNotFrench** [comment]
Closed with #319
