### ISSUE TITLE
Shorten exit sequence / provide option for faster exit

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#286]
Provide early exit option and/or speed up balloon flight sequence so it's half as long

**Comment by FranchNotFrench** [comment]
The balloon flight is a neverending loop, and while it could be sped up,
there isn't really a "half as long" version. The finish currently triggers
after 60 seconds but that's a bit arbitrary. I think it takes 120 seconds
for a full rotation but the rotation doesn't start until 30 seconds into
the flight. I like the current rotation speed... It's kind of chill.

I'm happy to trigger the finish earlier and/or give players a small button
to manually trigger the finish. But I don't know what seems like the right
duration for an auto-finish.

**Comment by paulkim26** [comment]
Yea the orbiting speed is fine, wouldn't want that faster. Just thinking of players who want to exit asap. A button sounds like an ideal solution. Would also help for if they decide to stay for the auto-finish and want to exit later w/o going through the menu. Overall I like it!

**Comment by paulkim26** [comment]
I've seen players in collab 1 who just couldn't wait to exit and I can imagine waiting for the exit would exacerbate a bad experience if they haven't been having fun

**Comment by FranchNotFrench** [comment]
Any preference on a button or lever (Steampunk) on the basket vs. a pull chain hung from the lantern? In either case, I'll disable their collider until the player teleports into the balloon.

**Comment by FranchNotFrench** [comment]
> 

I'm still not sure how you were able to watch my playthrough XD

**Comment by FranchNotFrench** [comment]
> I've seen players in collab 1 who just couldn't wait to exit and I can imagine waiting for the exit would exacerbate a bad experience if they haven't been having fun

I'm still not sure how you were able to watch my playthrough XD

**Comment by paulkim26** [comment]
Button/lever sounds good, have no strong preference
