### ISSUE TITLE
Exterior island on Science wing side could use slight scale up

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#29]
The exterior Science wing model had to be scaled up to cover up existing floor tiles. It's slightly pushing the existing boundaries of the island and clipping into some of the trees. Would say this is low priority as it's not terribly noticeable.

**Comment by FranchNotFrench** [comment]
Is this resolved? I believe you shrunk Science exterior rather than scaling up Duc's model which should accomplish the same thing

**Comment by chazzybuch** [comment]
Scaled down Science exterior
