### ISSUE TITLE
Gallery doors open a split second before it renders in

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#291]
Super low priority, but noticeable. 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/e2439a01-04a7-4f20-ae0a-546b1013f614)

**Comment by FranchNotFrench** [comment]
To clarify, this does not seem to happen when you hit the button to unlock the section. Only when it is already unlocked, then you walk back to lobby and the door closes, then you approach the door again to re-enter.

**Comment by paulkim26** [comment]
This happens to science too if I remember correctly

**Comment by FranchNotFrench** [comment]
Resolved with #317
