### ISSUE TITLE
History wing exterior clips into "Finish" catwalk, floor tiles clip out

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#30]
![20230606155057_1](https://github.com/paulkim26/collab-museum/assets/135690926/4544649b-0ffd-461c-8367-e4dcdca3247b)
Think the quick fix may be to "cheat" the exterior and animate it away from the atrium when the elevator travels up. Would open space for the hot air balloon, and cover up floor tiles. Alternatively could extend length of hallway in History

**Comment by paulkim26** [comment]
Created separate exterior that doesn't clip with catwalk in #77

**Comment by FranchNotFrench** [comment]
Thanks for tweaking this! I might still put a 90 degree turn in the catwalk
so the balloon has more negative space to play with.

**Comment by paulkim26** [comment]
Feel free to manipulate the section B exterior as needed if you need more space
