### ISSUE TITLE
Gallery triggered Audio + Section Complete immediately when using Bypass

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#301]
I entered the Science section using the Bypass + Access Scan (no Debug), then used Bypass to unlock History but didn't enter History, then used Bypass to unlock Gallery. Immediately when I did that, the Gallery start/finish Audio triggered and I got the Lua message saying the Gallery was complete.
![image](https://github.com/paulkim26/collab-museum/assets/114628499/d2ea478e-4daf-4f3d-9c9d-207d48cf345c)

**Comment by FranchNotFrench** [comment]
This shouldn't have anything to do with using the Lock bypass...it triggers the same actions as the normal keys.

**Comment by FranchNotFrench** [comment]
FWIW, I tried one time to reproduce this in the Published version and I was unable to.

**Comment by FranchNotFrench** [comment]
I just tried to reproduce this again in the Editor, and it didn't occur. I looked at the slot logic for the section key, since that seemed related to when this bug triggered. Possibly unrelated, but I am not familiar with the Medallion 1 and Medallion 2 locks that the slot is targeting. 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/699d17d7-7b7f-4794-bdca-c6871741f3ae)
![image](https://github.com/paulkim26/collab-museum/assets/114628499/922692a7-0ab6-4bc3-ae24-4fad73ad7857)
![image](https://github.com/paulkim26/collab-museum/assets/114628499/6e134e81-2883-433f-a2d5-fd051397efcb)

**Comment by FranchNotFrench** [comment]
With Gallery unlocking third (last), that should cause the Medallion to enable and the Key to disable, which made me think this might be related. Medallion 1 and Medallion 2 locks have inverted passcodes. i.e. for Art it is 3-2 and 2-3

**Comment by FranchNotFrench** [comment]
It does look like these double locks were part of my original design (but labeled differently), so I must have had a purpose for them that I can't remember. I can step through the logic again if needed but I think the solution will come down to suppressing the On Exit event.
![image](https://github.com/paulkim26/collab-museum/assets/114628499/c9e8a824-8101-430a-b7c0-32240bc47935)

**Comment by paulkim26** [comment]
I'm surprised this is still occurring, but sure if you have a solution go for it

**Comment by FranchNotFrench** [comment]
I think it's specifically occurring when the section lock unlocks, and it is the final section so it is disabling the key and showing the medallion. I don't think we contemplated that scenario when you de-parented the key + medallion+ trigger from the rest of the interior viz toggling.

**Comment by FranchNotFrench** [comment]
I'm not sure it has anything to do with entering/exiting a section. The trigger for showing the medallions is when the final key is slotted.

**Comment by FranchNotFrench** [comment]
...the issue not being showing the medallion, but rather hiding the key which could seemingly trigger an On Exit event on occasion.

**Comment by paulkim26** [comment]
That makes sense. In hindsight "on exit" is not ideal for mission critical events, especially - when combined with activators.

**Comment by FranchNotFrench** [comment]
It's too bad On Exit is as buggy as it is...there are times when you really need to know the instant a player picks something up. I don't know another way to detect that.

**Comment by FranchNotFrench** [comment]
Here, we could have worked around it and to your point, just used solving the final section meta puzzle to trigger the outro music and puzzle logic. But, I think I can fix it and I do like keeping them in limbo of sorts until they grab the key/medallion.
