### ISSUE TITLE
Switch hinge side of elevator door

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#31]
More a suggestion than a required change. When the elevator arrives in the atrium, just seems to make more sense to lead the player towards the creator card room oppose to the VIP room which would be initially locked. Also just feels a little tight when exiting elevator, not sure if obstacles could be adjusted slightly.

**Comment by FranchNotFrench** [comment]
Testing reply via email...

I intentionally route players toward the VIP room for two reasons, even
though it seems less efficient at first blush:

1) I want them to realize there is a VIP lounge and not be able to access
it immediately, to build some motivation and delayed gratification which I
pay off in the gift shop (where coincidentally, you can immediately access
the VIP Lounge without walking all the way back around)

2) I want players to see Duc's beautiful city scape before they can
continue the CCW loop around the Atrium, which is only visible in full from
behind the bird cage+ window.

If you can make a beeline to the creator cards room, neither of these
things might happen.

Other than that, I haven't given it any thought. :D

I appreciate the suggestion though / feel free to offer an alternative.

**Comment by chazzybuch** [comment]
Ah that all makes sense. Yeah the only other idea which I threw out during the playtest was having a second door on the backside of the elevator which would open at the atrium. I agree about Duc's exterior, and thought it would be cool to showcase the cityscape and the window pattern as a nice reveal on the trip up. But I imagine adding a 2nd door would require some substantial modification to the existing bird cage model and a bunch of extra logic. So not sure if it would be worth it / make sense given the work involved.

**Comment by chazzybuch** [comment]
Sounds good, like I said nothing is inherently broken was just throwing out the idea but don't want to over complicate. I'll close this up.
