### ISSUE TITLE
K01. Colourful Madness colours can desync

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#323]
People were seeing different colours on the entry pad. Should use something safer i.e. dials, continuous lock w/ no display, etc.

Found live on stream https://www.twitch.tv/sketchela

**Comment by FranchNotFrench** [comment]
Same comment as 338... I took a quick look at the logic here...only thing I can think of to try is to replace targeting reset pins, with targeting empties that send a bounced value to the lock to reset it. I've never been 100% confident in how Reset pins work and feel like this has tripped me up in the past, so I never use them.

**Comment by paulkim26** [comment]
This seems to have fixed itself somehow. Maybe unstable at launch with that build.
