### ISSUE TITLE
K01. Colourful Madness parquet box was missing its top + key item was glitching around

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#324]
They managed to get the item though.

Found live on stream https://www.twitch.tv/sketchela

**Comment by wollo77** [comment]
This is completely absurd, as the box is a single basic prop. I don't get how a basic prop can be partly gone. 😕

**Comment by paulkim26** [comment]
Maybe this is just a "wontfix"

**Comment by chazzybuch** [comment]
I'm sure a lot of wacky desync issues will continue to pop up that are simply beyond our control and more on Pine's side of things. Maybe just best to take screenshots and report them in the Pine Discord

**Comment by FranchNotFrench** [comment]
Not sure if this is related to #332

**Comment by paulkim26** [comment]
Appears so
