### ISSUE TITLE
Rube Goldberg Cat with fork is Pickable (Shouldn't be?)

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#331]
Doesn't break the puzzle, but unintuitive and unintentional, I'm pretty sure, since the fork hits the target. See here: https://discord.com/channels/449578254433517578/1124175407860695121/1131378489564614738

**Comment by paulkim26** [comment]
Yes let's get rid of it. Removing the cat makes the puzzle read harder.

**Comment by FranchNotFrench** [comment]
The cat with the knife is also pickable but that doesn't really make sense because if you grab the cat the knife is still sitting there. I think I'm inclined to make no cats pickable. They are cute but we don't have any other random pickable stuff in the museum and it is distracting players and leading to too many questions.

**Comment by FranchNotFrench** [comment]
Resolved with #338
