### ISSUE TITLE
Electricity from section A can be heard from lobby @ start

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#34]

**Comment by chazzybuch** [comment]
It's a weird glitch I haven't been able to sort out. None of those sound objects are set to Autostart and not sure what is triggering that single one. Oddly enough if I mark it to "Autostart", it turns off after a couple seconds, which is the "fix" I'm using right now. It has to be something with some of my trigger logic, but as the player doesn't start anywhere near any of the sound triggers I don't know how anything could be getting set off.

**Comment by chazzybuch** [comment]
Ah yeah... just noticing now I still hear one of them in the background. I'll take another look and try to sort it

**Comment by chazzybuch** [comment]
Looks like the Autoplay "fix" for that sound object didn't carry over from merge. So I can set it to Autoplay and it will only play for about 2 seconds and then go out until properly triggered again. This "fix" doesn't really make a lot of sense though as I still have no idea what's triggering it to play in the first place

**Comment by paulkim26** [comment]
I see, have you tried not relying on autoplay and starting the sound only when the science section is entered?

**Comment by paulkim26** [comment]
If the sound trigger can't be identified, could try deleting the sound object and recreating it to make sure nothing is linking to it

**Comment by chazzybuch** [comment]
Thought that was the first step I tried but I may be misremembering. I'll give it another crack
