### ISSUE TITLE
Science Meta puzzle incorrect passcode?

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#341]
I'm not sure which randomization this is, but at the 6 o'clock position with Planet size selected, Uranus is shown but it wants the Symbol for Mars. See video here. https://www.youtube.com/watch?v=VlhSZBoCuao

I cannot tell which randomization scenario 1-8 this is, but here are the passcodes for the eight Mercury locks. 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/a3a6fede-0fbf-467d-b270-66f16e95a034)

**Comment by FranchNotFrench** [comment]
I hooked up a Display to Mercury Lock 5 to see what values each symbol sends to the lock:
Mercury = 0
Venus = 1
Earth = 2
Mars = 3
Jupiter = 4
Saturn = 5
Uranus = 6
Neptune = 7

**Comment by FranchNotFrench** [comment]
In the video, from 12 o'clock and going clockwise, the symbols that unlocked the meta puzzle are:
Saturn (5) Saturn (5) Neptune (7) Mercury (0) Mars (3) Earth (2) Earth (2), Neptune (7). This matches Mercury Lock 4 although it is rotated.

**Comment by FranchNotFrench** [comment]
Should the 3 be a 6 (Uranus)? Any easy way to double check the rest?

**Comment by FranchNotFrench** [comment]
I would go through and test each, but I'm not sure how the randomization works.

**Comment by FranchNotFrench** [comment]
More discussion here: https://discord.com/channels/973804784148688926/1091799356203614268/1131822525295366284

**Comment by FranchNotFrench** [comment]
I have a thought on how to double check these as well...it occurs to me that the two orders are known, so it's just a matter of rotating those through the eight size/distance positions and then seeing which translate to which lock (though based on Chazzy's comments I'm pretty sure I get that now too...it's all about the Mercury, babby!)

**Comment by FranchNotFrench** [comment]
I froze the planets in the same position as the video, which should be Mercury 8 lock as Chazzy noted, and I was able to solve it by entering the planets I saw, and then confirmed that matched the Lock 8 passcode.

**Comment by FranchNotFrench** [comment]
Here are my additional notes. 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/95b9816f-b112-4909-a4b4-d75f81aa4b72)

**Comment by FranchNotFrench** [comment]
Rather than rotating the numbers, I rotated the distance/size labels. I couldn't quite figure out what to do with the Mercury pin, but Mercury is always in the same position regardless if it is distance from sun or size. Based on this, I convinced myself all the lock passcodes are correct. 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/1b562582-2123-47f1-a120-f5668de26618)

**Comment by FranchNotFrench** [comment]
What Lua script are these referencing? 
![image](https://github.com/paulkim26/collab-museum/assets/114628499/e3c0252b-70c5-40d8-aaa2-dd8e6ee9871c)

**Comment by paulkim26** [comment]
May or may not be linked to this issue, from pchoma:

> HI all, we are not done this escape yet but also experienced difficulty with the planets puzzle in the science room. Below there is info that says
"Zesty Mordant [author] 20 Jul @ 11:08pm
Hi Adrianna, the planets puzzle is randomly generated per user, so video walkthroughs won't line up with your session. If you're having trouble with the puzzle you can access the in-game walkthrough by pressing ESC to access the menu and clicking "Walkthrough". Hope that helps " but interestingly enough, 

https://steamcommunity.com/workshop/filedetails/discussion/2985569031/3801651661440150832/?ctp=2

**Comment by chazzybuch** [comment]
> What Lua script are these referencing? ![image](https://user-images.githubusercontent.com/114628499/255222440-e3c0252b-70c5-40d8-aaa2-dd8e6ee9871c.png)

Just added a commit to remove the old script variables
