### ISSUE TITLE
Debug mode activates for joining player

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#347]
Happens consistently for this user's session. Debug mode activates only for **joining** player. One of the players is running Windows 10 and the other is on MacOS.

Probably due to activator hiding debug buttons not firing on autostart. Not reported elsewhere. May be platform dependent issue. May not be worth fixing.

https://discordapp.com/channels/449578254433517578/1132629269986676796/1132629269986676796

**Comment by chazzybuch** [comment]
Probably overkill, but we could parent all debug logic to a single parent empty underneath, and at the center of the map. In addition to toggling them with vis activators, we could have them animate into place when activated. However if the "auto start" logic wasn't working in this instance, I'm sure there are other parts of the map that would've been broken as well.

**Comment by paulkim26** [comment]
That could work, at the very least keep things organized

In the end though yea this may just be a case of shooting fish in a barrel
