### ISSUE TITLE
DNA piece despawned and appeared in center of pendulum

### ISSUE THREAD

**Issue by FranchNotFrench** [paulkim26/collab-museum#348]
Seems like the DNA piece went to 0,0,0 instead of into player inventory. Maybe it isn't marked as a key? 

Approximate timestamp: this is just after it happened. https://www.twitch.tv/videos/1880646282?t=01h46m29s

**Comment by paulkim26** [comment]
Will investigate

**Comment by FranchNotFrench** [comment]
Here is a more precise timestamp, right when they lose GTC https://www.twitch.tv/videos/1880646282?t=01h42m32s
