### ISSUE TITLE
"Waiting for all players" not working properly

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#350]
> I got locked out of the science wing after finishing it the first time. Pressed sign to access, got "waiting for all players" and even after my coop partner got there, it didn't open and could no longer access the sign.

From TirusR: https://steamcommunity.com/workshop/filedetails/discussion/2985569031/3801651661440150832/?ctp=2

**Comment by FranchNotFrench** [comment]
This is kind of an unsatisfying kludge, but as long as at least one player can get back to the lobby, it occurs to me the nuclear option might be a button that does a hard reset - forces a state that we know is not bugged. It would be a mix of teleporting all players back to the lobby, locking each section, and forcing visibility of waiting signs and sections to how we want. Not sure how this would work in combination with the Atrium, but I've never heard of players getting stuck upstairs so it is probably fine.

It also occurs to me we could force the Museum section interiors to de-render during the balloon ride, on the outside chance one of them got stuck on (the bug I saw with my friend on Sunday morning).

**Comment by paulkim26** [comment]
That could work. Perhaps there can be a "Teleport Everyone Here" button underneath "Waiting for all players" that teleports all + forces safe state

**Comment by paulkim26** [comment]
I think it's good to force derendering of zones as you mention
