### ISSUE TITLE
Random leftover texture file from PR#28

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#36]
https://github.com/paulkim26/collab-museum/pull/28/files#diff-280813f7502c42a3822076453849623e215c3c7ec399f73acc834021e631bee9

**Comment by chazzybuch** [comment]
Ah sorry about that. Looks like there was already an instance of my "empty" PNG from my Art gallery module that I forgot about. You should be able to replace all instances of "yjkdjweuhi" with "tx_chazzyb_empty" in the Room file to sort it out.
