### ISSUE TITLE
Gap in section b floor

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#46]
<img width="1053" alt="image" src="https://github.com/paulkim26/collab-museum/assets/45007945/825f4f83-7e4b-4f10-9833-fee0da4bd7d4">

**Comment by paulkim26** [comment]
Steal section C floor

**Comment by chazzybuch** [comment]
Was going to say if this is fitting for you aesthetically, it may be worth just sneaking a black/brown plane underneath the floor. But  then realized swapping to the Section C parquet would make hiding it for the elevator ride much easier.

**Comment by paulkim26** [comment]
Yep can't use these current floors unfortunately

**Comment by paulkim26** [comment]
Floor recreated with props (rather than default floor editor) in #77
