### ISSUE TITLE
Fix Science meta puzzle z-fighting issues on Linux

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#51]
Thoroniul has reported having the space stickers pop out in front of the planet cards in the meta puzzle. Tough to reproduce without running a native Linux build myself.

**Comment by paulkim26** [comment]
Yea this is tricky, when I had to deal with this I just had to move out all potentially touching planes and ask Thoroniul to check each time. Don't think there's a better option other than running it on linux yourself

**Comment by paulkim26** [comment]
Don't these z-fighting issues also show up on deck?

**Comment by chazzybuch** [comment]
I'm running Proton and they currently don't, but it may make more sense to switch back to the native Linux build for this. Also seeing as the majority of players on Deck are probably not going out of their way to switch to the Proton build, it would be more representative of the performance most Deck players would be getting.

**Comment by paulkim26** [comment]
I'll install Linux and fix the z-fighting instances

**Comment by chazzybuch** [comment]
I think it may be a thing of replacing the space stickers with a different round object that only has rendered faces on one side. The stickers are existing on different coordinates than their parents, so not sure what would be causing the z-fighting.

Also there is a chance that because I took the rotation off of Lua and onto empty rotations that the result of the z-fighting stuff may have changed? Wouldn’t know until testing it out

**Comment by paulkim26** [comment]
Well noted, will see if its different this time

**Comment by paulkim26** [comment]
Tell everyone to run it on proton
