### ISSUE TITLE
Low/Medium/High Graphic Presets via Lobby & Host Pickable

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#52]
At some point I'd like to generate a prototype for some graphic preset options that players can switch between. This would primarily effect lighting, and may become particularly important for multiplayer games, especially for players with lower-end machines. 

Zesty suggested a permanent option in the Lobby, and I think it would also be useful to give the host a phone / tablet they can carry around to the different wings to see the graphics differences on the fly.

Each wing could have six Visibility Activators, 2 for each preset (low/medium/high) for enabling / disabling said options.

**Comment by paulkim26** [comment]
Either a stationary or pickable solution works for me. We can simplify it and just say each section needs 3 locks that the options interface points to, and leave the implementation up to each section

**Comment by chazzybuch** [comment]
3 locks does make more sense for sure. I think having both solutions is good, as players could inadvertently find someway to lose the pickable / throw it out of bounds (despite our best efforts).

**Comment by paulkim26** [comment]
Is this feature still on track or can we close under wontfix?
