### ISSUE TITLE
Science door should open faster on subsequent visits

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#67]

**Comment by chazzybuch** [comment]
I gotta modify the logic a bit to lose the initial door shift during the trigger zone open & closes, which will shave off 0.75 seconds. I'll probably still keep it whenever the door is initially activated on the panel for consistency. I'd like to keep the overall animation speed of the top and side doors opening where they're at for the moment, but I'll try to expand the trigger zone a touch so they open a bit earlier.

**Comment by FranchNotFrench** [comment]
I think we can mark this as complete?

**Comment by chazzybuch** [comment]
Yeah I think this is alright for now. Don't want to add any extra complications just before release
