### ISSUE TITLE
W01 (wollo slider puzzle) crashes upon zoom interaction in multiplayer

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#71]
Tested in a 2 player session with chazzy and zesty. Reproducible across multiple attempts.

Upon clicking zoom interaction, session seizes up and crashes.

Does not happen in unmerged module. Only in merged module. Possible regression from something else during merge. Or could be due to the overall complexity of the room.

**Comment by paulkim26** [comment]
Able to temporarily resolve issue by cutting some lua scripts in science wing (that control the text animations). The zoom interaction does hang for 1-2 seconds though.

Crash seems to be tied to overall complexity of room.

**Comment by chazzybuch** [comment]
Looks like the issue was not related to Lua scripts but colliders / zoomable settings. Setting Collider Type to "None" on the custom model walls in Art and resetting the zoomable position seems to be the temp fix for the moment. Still need to investigate "hitching" zoomables in Art & History wings
