### ISSUE TITLE
Remove negative scaling

### ISSUE THREAD

**Issue by wollo77** [paulkim26/collab-museum#72]
We see this message in the player log for lots of props:
```
BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider"
```

We want to look into either resizing these props to a positive scale if possible or setting their collider to none.

Full list of objects:
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/West/CornerSofa/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (4)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (5)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (6)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (7)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant3/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant3/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant3/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant3/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant2/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant2/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant2/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant2/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant1/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant1/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant1/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant1/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (4)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (5)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (6)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant5/Collider (7)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/V5Props/V5Plant4/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4PlanetRackLockingHinge/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4PlanetRackLockingHinge/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4PlanetRackLockingHinge/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4PlanetRackLockingHinge/Collider (3)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4PlanetRackLockingHinge/Collider (4)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4PlanetRackLockingHinge/Collider (5)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4PlanetRackLockingHinge/Collider (6)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/TransparentSingleSided/TransparentSingleSided
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/TransparentSingleSided/TransparentSingleSided
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/TransparentSingleSided/TransparentSingleSided/TransparentSingleSided
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/TransparentSingleSided/TransparentSingleSided
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/TransparentSingleSided/TransparentSingleSided/TransparentSingleSided
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/JailBarsDoorHandle
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/JailBarsDoorHandle
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/JailBarsDoorHandle
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/JailBarsDoorHandle
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/West/JailDoor/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Cube/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (36)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (37)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (38)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (39)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (40)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (41)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (42)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (43)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (44)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (45)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (46)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (47)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (48)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (49)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (50)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (51)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (52)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (53)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (54)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (55)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (36)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (37)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (38)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (39)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (40)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (41)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (42)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (43)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (44)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (45)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (46)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (47)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (48)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (49)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (50)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (51)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (52)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (53)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (54)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (55)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Plane/Base/V1Props/V1PictureFrameBigMan
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (36)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (37)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (38)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (39)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (40)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (41)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (42)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (43)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (44)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (45)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (46)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (47)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (48)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (49)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (50)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (51)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (52)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (53)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (54)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/V4Props/V4OuijaTableEmpty/Colliders/CornerTable (55)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_ivy/ivy_decimate_nopot.gltf-ivy_decimate_nopot.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/Base/Empty
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_ivy/ivy_decimate_nopot.gltf-ivy_decimate_nopot.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_topdome.gltf-dome2_topdome.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_topdome.gltf-dome2_topdome.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_topdome.gltf-dome2_topdome.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_topdome.gltf-dome2_topdome.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_windows.gltf-dome2_windows.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_windows.gltf-dome2_windows.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_windows.gltf-dome2_windows.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_windows.gltf-dome2_windows.gltf/custom_/mdl_franch_dome/dome2_windows.gltf-dome2_windows.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_base.gltf-dome2_base.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_base.gltf-dome2_base.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_base.gltf-dome2_base.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/Empty/custom_/mdl_franch_dome/dome2_base.gltf-dome2_base.gltf
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (2)
LevelContainerEditor/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider
LevelContainerEditor/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (1)
LevelContainerEditor/Base/Empty/Base/Empty/Base/S2/S2FloorPanel/WallProps/SpaceWallProp/Collider (2)

**Comment by chazzybuch** [comment]
At least for the corner sofas in the Lobby I think the inverse scaling is a necessity. Perhaps turning off the "Is Obstacle" setting on them and maybe disabling their colliders would help things if this is in fact causing an issue? Could replace with logic Obstacles

**Comment by paulkim26** [comment]
Not worth fixing it seems, feel free to reopen if needed.
