### ISSUE TITLE
Section doors are visible on 2nd floor

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#83]
![image](https://github.com/paulkim26/collab-museum/assets/45007945/1390dc36-c9af-4605-af96-5038d604e212)

**Comment by chazzybuch** [comment]
Ah, side effect of the de-parenting from Drag Lobby I think.

**Comment by FranchNotFrench** [comment]
This one doesn't seem like it should be assigned to me...I don't currently
have anything to do with the section doors. :D

I'm keeping track of all these, but also I need to stay focused on wrapping
up my stuff first. At some point I'll figure out how to do the GitHub thing
and be a more active contributor to fixing bugs for anything that still
needs to be resolved.
