### ISSUE TITLE
Merge in updated L02 (fixed bug where machine becomes unresponsive)

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#9]

**Comment by paulkim26** [comment]
Breaks sometimes. Need to find repro.

**Comment by paulkim26** [comment]
<img width="801" alt="image" src="https://github.com/paulkim26/collab-museum/assets/45007945/f2777c1e-2d4a-4102-ab06-f6b590892707">

Button becomes unresponsive

**Comment by paulkim26** [comment]
This seems to be working now? @chazzybuch did you happen to fix this or am I tripping

**Comment by chazzybuch** [comment]
Nah haven't touched it. It has generally worked for me in single player, multiplayer is where the desync issues seem to always pop up

**Comment by chazzybuch** [comment]
Reopened for now, but maybe we get lucky and it'll be working fine after the update next week

**Comment by paulkim26** [comment]
hm ic, well noted. There was a bug where the button would get stuck in single player that doesn't seem to happen anymore. This mp desync is news to me and looks like another issue.

**Comment by chazzybuch** [comment]
I did notice that with the horse but it seemed once you moved it back and forth it would sort itself out. This also seems to be the work around for MP. You need to move the pieces back & forth to their correct positions.

**Comment by chazzybuch** [comment]
This is POSSIBLY solved with the next official ES update. Waiting for further testing after the update before I close this

**Comment by paulkim26** [comment]
Replace trigger logic with locks

**Comment by paulkim26** [comment]
Video of repro: https://youtu.be/ERMZ9GuUNUE

**Comment by chazzybuch** [comment]
I dont recall Leo ever updating module, so if it was always done with locks
should we try triggers instead? Not sure why I assumed it already was being
done with triggers, if I heard from Leo or someone else and never inspected
closely enough in the editor

**Comment by paulkim26** [comment]
mightve been me that assumed it was triggers, welp. Triggers could work, though a lock based solution that works properly would be ideal. Hopefully leo can figure it out now with the video

**Comment by paulkim26** [comment]
To merge in: http://steamcommunity.com/sharedfiles/filedetails/?id=2996832554

**Comment by paulkim26** [comment]
The updated module is broken, should not be imported.
