### ISSUE TITLE
Place section keys in their respective sections

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#91]
Need instructions for this process, possible snafus, etc.

**Comment by chazzybuch** [comment]
Just moving them from the initial spots in the lobby to wherever they'll be spawning should work. I had to do a little vis activator swap trick to get the medallion to fit in the Science meta container, and looks like Art may need to do something similar. Unless the hex container was scaled up.

**Comment by paulkim26** [comment]
Thanks, will take a look

**Comment by paulkim26** [comment]
Completed in pr #98
