### ISSUE TITLE
Using debug button to open science wing prevents testers from backing out.

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#96]
Minor bug, only affects testing + development

Repro:
- Press debug button to open science wing
- Go inside
- Wait for door to close
- Try to go back to lobby
- Won't open

![image](https://github.com/paulkim26/collab-museum/assets/45007945/03157a76-7969-49ae-99b6-431ec4d18b1c)

**Comment by chazzybuch** [comment]
Hmm door trigger should still be coming up with the debug, I'll take a look

**Comment by chazzybuch** [comment]
Didn't put it in the notes, but this is "fixed" in #97. But the tunnel audio will glitch out when using the Debug open.
